### ISSUE TITLE
Make specific languages linkable

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/atomlinter.github.io#17]
Right now it seems it isn't possible to link a specific language's linters on the site.

**Comment by kepler0** [comment]
I'm not sure I understand. Are you talking about links like https://atomlinter.github.io/#language-c?

**Comment by Arcanemagus** [comment]
Yes, essentially make links like that work instead of just showing the home page.

**Comment by kepler0** [comment]
Fixed with Material redesign.

**Comment by Arcanemagus** [comment]
Amazing ob on the redesign, but how do you link users to a specific language? :stuck_out_tongue:

**Comment by kepler0** [comment]
Try the link I posted above. :wink:

**Comment by Arcanemagus** [comment]
Apparently I'm blind when I looked at dev tools.
