### ISSUE TITLE
Document how to add a linter

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/atomlinter.github.io#31]
Recently there was [a question](https://github.com/atom-community/linter/issues/1067) posted to the `linter` repo on how to add a plugin to the list, it might help if we have a note somewhere on the site saying how to add a linter here.

**Comment by kepler0** [comment]
GitHub repo ribbon?

**Comment by Arcanemagus** [comment]
That's probably good enough, anyone adding a plugin would be a developer and should know what that means.

**Comment by kepler0** [comment]
Cool. I'll make the addition toward the end of the day.
