### ISSUE TITLE
Links in the drawer

### ISSUE THREAD

**Issue by chadluo** [AtomLinter/atomlinter.github.io#37]
The current version of the page uses a navigational drawer from the MDL library, triggered from the hamburger icon on the top left corner. However the contents of the drawer are the same as the links in the navigation bar, and the drawer did not make its use.

What I wanted to do and presented in a previous [pull request](https://github.com/AtomLinter/atomlinter.github.io/pull/36) is to change the content to the four categories of linter groups (languages, IDEs, generic linters and linter plugins).

This change will improve the navigation by making it easier to locate a certain category of linters from the drawer, and the role of the drawer will not overlap the links in the navigation bar.

The following is a preview of how it will look like.
![image](https://cloud.githubusercontent.com/assets/3235854/13912176/65d22c2c-ef8e-11e5-9102-5d11134fb20d.png)

This is a rather small but kind of useful change, and perhaps the least controversial change among those in my original pull request. If you are happy with it, I will be glad to put this up.

**Comment by keplersj** [comment]
Looks great!
