### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by chadluo** [AtomLinter/atomlinter.github.io#44]
The current version of the page occupies by default the whole width of the page, making the cards too wide to scan through and leaving too much space between them.

I managed to reduce the width of the cards without squeezing them too tight, and you can refer to this screenshot:

![image](https://cloud.githubusercontent.com/assets/3235854/14065268/f1480fc6-f46e-11e5-9a42-caaf7291fbae.png)

I wanted to change the background color of the page to light gray since white cards with drop shadows does not look good on the white background, but a gray background does not cope well with the beige banner. I am still working on that, and I shall come with some other solutions later.

If you are happy with this, I can just put this on.

**Comment by keplersj** [comment]
Puurrrrrty.

**Comment by keplersj** [comment]
Mind doing it in a PR so I can see it before merge?

**Comment by keplersj** [comment]
Direct posting to master scares me.

**Comment by chadluo** [comment]
It's fine doing a PR. I said I won't push without your approval.

**Comment by keplersj** [comment]
Yay! Thank you.
