### ISSUE TITLE
Split Language Specific Linters by Static Analysis and Style Linters.

### ISSUE THREAD

**Issue by kepler0** [AtomLinter/atomlinter.github.io#9]

**Comment by k2b6s9j** [comment]
Maybe Compilers should be their own section?

**Comment by k2b6s9j** [comment]
@steelbrain Opinion?

**Comment by steelbrain** [comment]
@k2b6s9j IMO. Splitting them via language is enough, 'cause we don't have tons of them just yet. When we have tons of them per language in the future, we can re-consider splitting them

**Comment by k2b6s9j** [comment]
Alright.

**Comment by kepler0** [comment]
Now that linter categories are linkable this gets more difficult. Throwing the idea aside for now.

This should be revisited when the registry grows larger though.
